---
- name: Java and Tomcat Installation
  hosts: Application_Servers
  vars:
    req_java: jav-1.8.0-openjdk
    req_tomcat_ver: 8.5.55
    tomcat_url: https://mirrors.estointernet.in/apache/tomcat/tomcat-{{req_tomcat_ver.split('.')[5]}}/v{{req_tomcat_ver}}/bin/apache-tomcat-{{req_tomcat_ver}}.tar.gz
    tomcat_port: 8090
    tomcat_secure_port: 8093
  become: true

  tasks:

  - name: Updating Repos
    yum:
     name: "*"
     state: latest

  - name: Java Installation
    yum:
     name: "{{req_java}}"
     state: present

  - name: Downloading Tomcat
    get_url: 
      url: {{tomcat_url}}
      dest: /opt

  - name: Extracting Downloaded Tomcat
    unarchive: 
      src: "/opt/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
      dest: /opt
      remote_src: yes

  - name: Renaming Tomcat Home
    command: mv /opt/apache-tomcat-{{req_tomcat_ver}} /opt/tomcat

  - name: Replacing default port with required port
    template: 
      src: server.xml.j2
      dest: /opt/tomcat/conf/server.xml
  
  - name: Adding roles and username and password in tomcat-user.xml
    template: 
      src: tomcat-users.xml.j2
      dest: /opt/tomcat/conf/tomcat-users.xml

  - name: Commenting Values or Class attributes in context.xml for host-manager
    template: 
      src: context.xml.j2
      dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml

  - name: Commenting Values or Class attributes in context.xml for manager
    template: 
      src: context.xml.j2
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml

  - name: Starting Tomcat
    shell: nohup /opt/tomcat/bin/startup.sh &